OPC_SERVER = 'Matrikon.OPC.Simulation'
OPC_HOST = 'localhost'
ARN_TOPIC = 'arn:aws:sns:us-east-1:650730994064:simulation_read'
AWS_REGION_NAME = 'us-east-1'
CSV_FILENAME = 'Logs 04-10-2023.csv'
READ_SECONDS = 1
TAGS_READ = [
  # 'Controlador.PC1.OUT',
  # 'Drum.V1.L',
  # 'Drum.V1.P',
  # 'Drum.V1.T',
  # 'Drum.V1.VOL',
  # 'Source.SRC1.PB',
  # 'StreamSend.FLARE.P',
  # 'StreamSend.SAIDA_GAS.P',
  # 'StreamSend.SAIDA_LIQUIDO.P',
  # 'Transmissor.TR1.OUT',
  # 'Transmissor.TR2.OUT',
  # 'Transmissor.TR3.OUT',
  # 'Tubo.S1.P',
  # 'Tubo.S1.T',
  # 'Tubo.S1.W',
  # 'Tubo.S10.P',
  # 'Tubo.S10.T',
  # 'Tubo.S10.W',
  # 'Tubo.S2.P',
  # 'Tubo.S2.T',
  # 'Tubo.S2.W',
  # 'Tubo.S25.P',
  # 'Tubo.S25.T',
  # 'Tubo.S25.W',
  # 'Tubo.S26.P',
  # 'Tubo.S26.T',
  # 'Tubo.S26.W',
  # 'Tubo.S27.P',
  # 'Tubo.S27.T',
  # 'Tubo.S27.W',
  # 'Tubo.S28.P',
  # 'Tubo.S28.T',
  # 'Tubo.S28.W',
  # 'Tubo.S3.P',
  # 'Tubo.S3.T',
  # 'Tubo.S3.W',
  # 'Tubo.S4.P',
  # 'Tubo.S4.T',
  # 'Tubo.S4.W',
  # 'Tubo.S5.P',
  # 'Tubo.S5.T',
  # 'Tubo.S5.W',
  # 'Tubo.S6.P',
  # 'Tubo.S6.T',
  # 'Tubo.S6.W',
  # 'Valvula.VALVE1.CL',
  # 'Valvula.VALVE1.OP',
  # 'Valvula.VALVE1.STOP',
  # 'Valvula.VALVE1.DP',
  # 'Valvula.VALVE2.CL',
  # 'Valvula.VALVE2.OP',
  # 'Valvula.VALVE2.DP',
  # 'Valvula.VALVE3.OP',
  # 'Valvula.VALVE3.DP',
  # 'Valvula.VALVE4.CL',
  # 'Valvula.VALVE4.OP',
  # 'Valvula.VALVE5.CL',
  # 'Valvula.VALVE5.OP',
  # 'Valvula.VALVE5.DP',
  # 'Valvula.VALVE_SHUTOFF.CL',
  # 'Valvula.VALVE_SHUTOFF.OP',
  # 'Valvula.VALVE_SHUTOFF.DP',
  # 'Variaveis.VOTACAO_TRANSMISSORES',
  # 'Variaveis.TR1_RUIDO',
  # 'Variaveis.TR2_RUIDO',
  # 'Variaveis.TR3_RUIDO'

  'Variaveis.TR1_RUIDO',
  'Variaveis.TR2_RUIDO',
  'Variaveis.TR3_RUIDO',
  # 'Variaveis.PUMP_FALHA',
  # 'Variaveis.DTS',
  # 'Variaveis.DPS',
  # 'Variaveis.OP_SHUTOFF',
  'Variaveis.H2O_QTD',
  # 'Variaveis.OP_CONCESSIONARIA',
  'Valvula.VALVE5.OP',
  'Variaveis.VOTACAO_TRANSMISSORES',
  # 'Variaveis.LIMITE_LIQUIDO',
  # 'Variaveis.MINIMO_LIQUIDO',
  #'Valvula.VALVE_RESPIRO.CL',
  'Valvula.VALVE_RESPIRO.OP',
  'Valvula.VALVE_RESPIRO.L',
  'StreamSend.FLARE.P',
  # 'Valvula.VALVE3.CL',
  'Valvula.VALVE3.OP',
  'Valvula.VALVE3.L',
  'StreamSend.SAIDA_GAS.P',
  # 'Valvula.VALVE2.CL',
  'Valvula.VALVE2.OP',
  'Valvula.VALVE2.L',
  # 'Valvula.VALVE1.CL',
  'Valvula.VALVE1.OP',
  'Valvula.VALVE1.L',
  # 'Valvula.VALVE_SHUTOFF.CL',
  'Valvula.VALVE_SHUTOFF.OP',
  'Valvula.VALVE_SHUTOFF.L',
  # 'Valvula.VALVE6.OP',
  # 'Valvula.VALVE6.L',
  'StreamSend.SAIDA_LIQUIDO.P',
  'Valvula.VALVE4.OP',
  'Valvula.VALVE4.L',
  'StreamSend.SAIDA_VAZAMENTO.P',
  'Valvula.VALVE5.L',
  'Transmissor.TR1.OUT',
  'Transmissor.TR2.OUT',
  'Transmissor.TR3.OUT',
  'Drum.V1.L',
  'Drum.V1.P',
  'Drum.V1.T',
  # 'Drum.V1.VOL',
  'Tubo.S1.P',
  # 'Tubo.S1.T',
  # 'Tubo.S1.Q',
  # 'Tubo.S1.F',
  'Tubo.S1.W',
  'Tubo.S2.P',
  # 'Tubo.S2.T',
  # 'Tubo.S2.Q',
  # 'Tubo.S2.F',
  'Tubo.S2.W',
  'Tubo.S6.P',
  # 'Tubo.S6.T',
  # 'Tubo.S6.Q',
  # 'Tubo.S6.F',
  'Tubo.S6.W',
  # 'Tubo.S7.P',
  # 'Tubo.S7.T',
  # 'Tubo.S7.Q',
  # 'Tubo.S7.F',
  # 'Tubo.S7.W',
  # 'Tubo.S8.P',
  # 'Tubo.S8.T',
  # 'Tubo.S8.Q',
  # 'Tubo.S8.F',
  # 'Tubo.S8.W',
  # 'Tubo.S9.P',
  # 'Tubo.S9.T',
  # 'Tubo.S9.Q',
  # 'Tubo.S9.F',
  # 'Tubo.S9.W',
  # 'Tubo.S12.P',
  # 'Tubo.S12.T',
  # 'Tubo.S12.Q',
  # 'Tubo.S12.F',
  # 'Tubo.S12.W',
  'Tubo.S5.P',
  # 'Tubo.S5.T',
  # 'Tubo.S5.Q',
  # 'Tubo.S5.F',
  'Tubo.S5.W',
  'Tubo.S10.P',
  # 'Tubo.S10.T',
  # 'Tubo.S10.Q',
  # 'Tubo.S10.F',
  'Tubo.S10.W',
  'Tubo.S3.P',
  # 'Tubo.S3.T',
  # 'Tubo.S3.Q',
  # 'Tubo.S3.F',
  'Tubo.S3.W',
  'Tubo.S4.P',
  # 'Tubo.S4.T',
  # 'Tubo.S4.Q',
  # 'Tubo.S4.F',
  'Tubo.S4.W',
  'Tubo.S25.P',
  # 'Tubo.S25.T',
  # 'Tubo.S25.Q',
  # 'Tubo.S25.F',
  'Tubo.S25.W',
  'Tubo.S26.P',
  # 'Tubo.S26.T',
  # 'Tubo.S26.Q',
  # 'Tubo.S26.F',
  'Tubo.S26.W',
  'Tubo.S27.P',
  # 'Tubo.S27.T',
  # 'Tubo.S27.Q',
  # 'Tubo.S27.F',
  'Tubo.S27.W',
  'Tubo.S28.P',
  # 'Tubo.S28.T',
  # 'Tubo.S28.Q',
  # 'Tubo.S28.F',
  'Tubo.S28.W',
  'Controlador.PC1.OUT',
  'Controlador.PID1.OUT',
  'Controlador.PID2.OUT',
  'Controlador.PID3.OUT'
]