OPC_SERVER = 'Matrikon.OPC.Simulation'
OPC_HOST = 'localhost'
ARN_TOPIC = 'arn:aws:sns:us-east-1:650730994064:simulation_read'
AWS_REGION_NAME = 'us-east-1'
CSV_FILENAME = 'Logs 26-05-2023.csv'
READ_SECONDS = 1
TAGS_READ = [
  'Controlador.PC1.OUT',
  'Drum.V1.L',
  'Drum.V1.P',
  'Drum.V1.T',
  'Drum.V1.VOL',
  'Source.SRC1.PB',
  'StreamSend.FLARE.P',
  'StreamSend.SAIDA_GAS.P',
  'StreamSend.SAIDA_LIQUIDO.P',
  'Transmissor.TR1.OUT',
  'Transmissor.TR2.OUT',
  'Transmissor.TR3.OUT',
  'Tubo.S1.P',
  'Tubo.S1.T',
  'Tubo.S1.W',
  'Tubo.S10.P',
  'Tubo.S10.T',
  'Tubo.S10.W',
  'Tubo.S2.P',
  'Tubo.S2.T',
  'Tubo.S2.W',
  'Tubo.S25.P',
  'Tubo.S25.T',
  'Tubo.S25.W',
  'Tubo.S26.P',
  'Tubo.S26.T',
  'Tubo.S26.W',
  'Tubo.S27.P',
  'Tubo.S27.T',
  'Tubo.S27.W',
  'Tubo.S28.P',
  'Tubo.S28.T',
  'Tubo.S28.W',
  'Tubo.S3.P',
  'Tubo.S3.T',
  'Tubo.S3.W',
  'Tubo.S4.P',
  'Tubo.S4.T',
  'Tubo.S4.W',
  'Tubo.S5.P',
  'Tubo.S5.T',
  'Tubo.S5.W',
  'Tubo.S6.P',
  'Tubo.S6.T',
  'Tubo.S6.W',
  'Valvula.VALVE1.CL',
  'Valvula.VALVE1.OP',
  'Valvula.VALVE1.STOP',
  'Valvula.VALVE1.DP',
  'Valvula.VALVE2.CL',
  'Valvula.VALVE2.OP',
  'Valvula.VALVE2.DP',
  'Valvula.VALVE3.OP',
  'Valvula.VALVE3.DP',
  'Valvula.VALVE4.CL',
  'Valvula.VALVE4.OP',
  'Valvula.VALVE5.CL',
  'Valvula.VALVE5.OP',
  'Valvula.VALVE5.DP',
  'Valvula.VALVE_SHUTOFF.CL',
  'Valvula.VALVE_SHUTOFF.OP',
  'Valvula.VALVE_SHUTOFF.DP',
  'Variaveis.VOTACAO_TRANSMISSORES',
  'Variaveis.TR1_RUIDO',
  'Variaveis.TR2_RUIDO',
  'Variaveis.TR3_RUIDO'
]