OPC_SERVER = 'Matrikon.OPC.Simulation'
OPC_HOST = 'localhost'
READ_SECONDS = 1
TAGS_READ = [
  'Variaveis.H2O_QTD',
  'Valvula.VALVE5.OP',
  'Variaveis.VOTACAO_TRANSMISSORES',
  'Valvula.VALVE_RESPIRO.OP',
  'Valvula.VALVE_RESPIRO.L',
  'StreamSend.FLARE.P',
  'Valvula.VALVE3.OP',
  'Valvula.VALVE3.L',
  'StreamSend.SAIDA_GAS.P',
  'Valvula.VALVE2.OP',
  'Valvula.VALVE2.L',
  'Valvula.VALVE1.OP',
  'Valvula.VALVE1.L',
  'Valvula.VALVE_SHUTOFF.OP',
  'Valvula.VALVE_SHUTOFF.L',
  'StreamSend.SAIDA_LIQUIDO.P',
  'Valvula.VALVE4.OP',
  'Valvula.VALVE4.L',
  'StreamSend.SAIDA_VAZAMENTO.P',
  'Valvula.VALVE5.L',
  # 'Transmissor.TR1.OUT',
  # 'Transmissor.TR2.OUT',
  # 'Transmissor.TR3.OUT',
  'Drum.V1.L',
  'Drum.V1.P',
  'Drum.V1.T',
  'Tubo.S1.P',
  'Tubo.S1.W',
  'Tubo.S2.P',
  'Tubo.S2.W',
  'Tubo.S6.P',
  'Tubo.S6.W',
  'Tubo.S5.P',
  'Tubo.S5.W',
  'Tubo.S10.P',
  'Tubo.S10.W',
  'Tubo.S3.P',
  'Tubo.S3.W',
  'Tubo.S4.P',
  'Tubo.S4.W',
  'Tubo.S25.P',
  'Tubo.S25.W',
  'Tubo.S26.P',
  'Tubo.S26.W',
  'Tubo.S27.P',
  'Tubo.S27.W',
  'Tubo.S28.P',
  'Tubo.S28.W',
  'Controlador.PC1.OUT',
  'Controlador.PID1.OUT',
  'Controlador.PID2.OUT',
  'Controlador.PID3.OUT'
]